---
driver:
  name: dokken
  privileged: true
  volumes: [
    '/var/lib/docker'
  ]

transport:
  name: dokken

provisioner:
  chef_license: accept
  name: dokken
  product_name: chef

verifier:
  name: inspec
  inspec_tests:
    - path: test/integration/default

platforms:
  - name: amazonlinux
    driver:
      image: dokken/amazonlinux
      pid_one_command: /sbin/init

  - name: amazonlinux-2
    driver:
      image: dokken/amazonlinux-2
      pid_one_command: /usr/lib/systemd/systemd

  - name: debian-8
    driver:
      image: dokken/debian-8
      pid_one_command: /bin/systemd

  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd

  - name: debian-10
    driver:
      image: dokken/debian-10
      pid_one_command: /bin/systemd

  - name: centos-7
    driver:
      image: dokken/centos-7
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd

  - name: fedora-30
    driver:
      image: dokken/fedora-30
      pid_one_command: /usr/lib/systemd/systemd

  - name: fedora-31
    driver:
      image: dokken/fedora-31
      pid_one_command: /usr/lib/systemd/systemd

  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd

  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd

  - name: ubuntu-20.04
    driver:
      image: dokken/ubuntu-20.04
      pid_one_command: /bin/systemd

suites:
  - name: chef-14
    run_list:
      - recipe[testrig]
    driver:
      chef_version: 14
    attributes:
      prometheus_exporters:
        node:
          collectors_disabled: ["wifi"]
  - name: chef-15
    run_list:
      - recipe[testrig]
    driver:
      chef_version: 15
    attributes:
      prometheus_exporters:
        node:
          collectors_disabled: ["wifi"]
  - name: chef-16
    run_list:
      - recipe[testrig]
    driver:
      chef_version: 16
    attributes:
      prometheus_exporters:
        node:
          collectors_disabled: ["wifi"]
  - name: chef-17
    run_list:
      - recipe[testrig]
    driver:
      chef_version: 17
    attributes:
      prometheus_exporters:
        node:
          collectors_disabled: ["wifi"]
